### Stage 1
FROM node:19-slim AS builder

WORKDIR /usr/src/app
COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install 

COPY . .

EXPOSE 3000

ENV REACT_APP_BASE_URL=http://localhost:8000

RUN npm run build

## Stage 2
## copy to caddy
FROM caddy:2.6.4-alpine

ARG CADDYFILE 
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv
EXPOSE 80
EXPOSE 443