const UserTypes = {
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    LOGOUT_USER: 'LOGOUT_USER',
}

export default UserTypes